name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache spaCy & NLTK models
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            ~/nltk_data
          key: ${{ runner.os }}-nlp-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage spacy nltk

      - name: Download NLP resources (spaCy + WordNet)
        run: |
          python -m spacy download en_core_web_lg
          python -c "import nltk; nltk.download('wordnet_ic')"

      - name: Run unittests with coverage
        run: |
          coverage run --rcfile=.coveragerc -m unittest discover -s ./tests -p "test_*.py"
          coverage xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=luxas-lxo_UML_Benchmark
            -Dsonar.organization=luxas-lxo
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/tests/**,**/*_test.py,z_main_test.py,LLM_response_generation/**
